---
abstract: 'An easy and convenient way to test Ext.Direct code'
author:
  - 'Alex Tokarev <tokarev@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-ExtDirect
no_index:
  directory:
    - t
    - inc
requires:
  RPC::ExtDirect::Client: '1.00'
  RPC::ExtDirect::Server: '1.00'
resources:
  bugtracker: http://github.com/nohuhu/Test-ExtDirect/issues
  repository: http://github.com/nohuhu/Test-ExtDirect
version: '1.00'
