---
abstract: 'An easy and convenient way to test Ext.Direct classes'
author:
  - 'Alex Tokarev <tokarev@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-ExtDirect
no_index:
  directory:
    - t
    - inc
requires:
  Clone: 0
  RPC::ExtDirect::Client: 0.2
  RPC::ExtDirect::Server: 0
  Test::More: 0
resources:
  bugtracker: http://github.com/nohuhu/Test-ExtDirect/issues
  repository: http://github.com/nohuhu/Test-ExtDirect
version: 0.22
